server:
  port: 10086
spring:
  application:
    name: gateway
  cloud:
    gateway:
      #配置路由网关的路由规则
      routes:
        - uri: lb://WEB-USER
          predicates:
            - Path=/user/**,/res/**
        - uri: lb://WEB-FRIEND
          predicates:
            - Path=/request/**,/friends/**
        - uri: lb://WEB-MSG
          predicates:
            - Path=/chat/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka