server:
  port: 9001
spring:
  application:
    name: web-friend
  datasource:
    url: jdbc:mysql:///wechat
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka